### ISSUE TITLE
Bug após a alteração skipRootObject da camcima/camcima-soap-client

### ISSUE THREAD

**Issue by maiconsasse** [camcima/mundipagg-php-client#4]
Boa Tarde

Após atualizar o composer do meu projeto as transações da mundipagg apresentam erro. 
Debugando vi que a causa foi a alteração "skipRootObject" no repositório "camcima/camcima-soap-client".
Para voltar a funcionar tive que alterar na classe Camcima\Soap\Client onde chamava o mapSoapResult para passar o parâmetro como TRUE.

**Comment by thomashs** [comment]
Fez um PR?

**Comment by maiconsasse** [comment]
Não fiz localmente nos meus programas e relatei o bug. Mas posso fazer se quiser...

**Comment by thomashs** [comment]
Testa e atualiza aqui pra comunidade :)

**Comment by camcima** [comment]
Já "mergeei" o PR. Fechando essa issue.
